.PHONY: run test lint build docker-build docker-run tidy openapi

ADDR ?= :8080
DATABASE_PATH ?= ./data/chargepoints.db
IMAGE ?= chargepoints-api:local
SWAG ?= $(shell go env GOPATH)/bin/swag

run:
	ADDR=$(ADDR) DATABASE_PATH=$(DATABASE_PATH) go run ./cmd/server

test:
	go test ./...

lint:
	@command -v golangci-lint >/dev/null || { echo "install: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b \$$(go env GOPATH)/bin v2.12.2"; exit 1; }
	golangci-lint run ./...

build:
	CGO_ENABLED=0 go build -o bin/server ./cmd/server

tidy:
	go mod tidy

# Regenerate api/openapi.yaml from swag annotations on handlers.
openapi:
	@command -v $(SWAG) >/dev/null || go install github.com/swaggo/swag/cmd/swag@v1.16.6
	$(SWAG) init \
		-g main.go \
		-d ./cmd/server,./internal/server,./pkg/chargepoint \
		-o ./api \
		--outputTypes yaml \
		--parseDependency \
		--parseInternal
	mv ./api/swagger.yaml ./api/openapi.yaml
	@printf '%s\n' \
		'# Code generated by swag. DO NOT EDIT.' \
		'# Source: make openapi (swag annotations on handlers).' \
		'' | cat - ./api/openapi.yaml > ./api/openapi.yaml.tmp && mv ./api/openapi.yaml.tmp ./api/openapi.yaml

docker-build:
	docker build -t $(IMAGE) .

docker-run:
	docker run --rm -p 8080:8080 -e ADDR=:8080 -e DATABASE_PATH=/data/chargepoints.db -v eco-cp-data:/data $(IMAGE)
